/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wf_news_util_NDKUtil */

#ifndef _Included_com_wf_news_util_NDKUtil
#define _Included_com_wf_news_util_NDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wf_news_util_NDKUtil
 * Method:    getStringFromNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wf_news_util_NDKUtil_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_wf_news_util_NDKUtil
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wf_news_util_NDKUtil_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
